/**
 * Project status / brief / decision-memo generators (Phase 6E).
 * LOCAL markdown drafts only — nothing is sent. No financial/legal/medical advice.
 */

export type UpdateKind = "status" | "brief" | "blocker" | "decision_memo" | "stakeholder" | "next_actions";

export interface StatusContext {
  title: string;
  progressPct: number;
  totalTasks: number;
  doneTasks: number;
  blockedTasks: number;
  overdueTasks: number;
  topRisks: string[];
  nextTasks: string[];
  targetDate?: string | null;
  owner?: string | null;
}

const FOOTER = "\n\n_Local draft generated by Personal Assist OS — not sent. Decision support only._";

export function buildProjectUpdate(kind: UpdateKind, ctx: StatusContext): { title: string; body: string } {
  const risks = ctx.topRisks.length ? ctx.topRisks.map((r) => `- ${r}`).join("\n") : "- None flagged.";
  const next = ctx.nextTasks.length ? ctx.nextTasks.map((t) => `- ${t}`).join("\n") : "- (no open tasks)";

  if (kind === "brief") {
    return {
      title: `Brief: ${ctx.title}`,
      body: `# ${ctx.title} — Project Brief\n\n**Owner:** ${ctx.owner || "—"}  \n**Target:** ${ctx.targetDate || "—"}  \n**Progress:** ${ctx.progressPct}% (${ctx.doneTasks}/${ctx.totalTasks} tasks)\n\n## Risks\n${risks}\n\n## Next actions\n${next}${FOOTER}`,
    };
  }
  if (kind === "blocker") {
    return {
      title: `Blockers: ${ctx.title}`,
      body: `# ${ctx.title} — Blockers\n\n${ctx.blockedTasks} blocked task(s), ${ctx.overdueTasks} overdue.\n\n## Risks\n${risks}\n\n## Unblock next\n${next}${FOOTER}`,
    };
  }
  if (kind === "decision_memo") {
    return {
      title: `Decision memo: ${ctx.title}`,
      body: `# ${ctx.title} — Decision Memo\n\n**Context:** ${ctx.progressPct}% complete, ${ctx.blockedTasks} blocked, ${ctx.overdueTasks} overdue.\n\n**Options:**\n1. Continue as planned.\n2. Re-scope to hit the target date.\n3. Extend the timeline.\n\n**Recommendation:** _fill in_.\n\n**Risks:**\n${risks}${FOOTER}`,
    };
  }
  if (kind === "stakeholder") {
    return {
      title: `Stakeholder update: ${ctx.title}`,
      body: `# ${ctx.title} — Stakeholder Update\n\nWe're ${ctx.progressPct}% complete (${ctx.doneTasks}/${ctx.totalTasks} tasks). ${ctx.overdueTasks > 0 ? `${ctx.overdueTasks} item(s) are behind.` : "On track."}\n\n**What's next:**\n${next}\n\n**Watch items:**\n${risks}${FOOTER}`,
    };
  }
  if (kind === "next_actions") {
    return { title: `Next actions: ${ctx.title}`, body: `# ${ctx.title} — Next Actions\n\n${next}${FOOTER}` };
  }
  // status
  return {
    title: `Status: ${ctx.title}`,
    body: `# ${ctx.title} — Weekly Status\n\n**Progress:** ${ctx.progressPct}% (${ctx.doneTasks}/${ctx.totalTasks})  \n**Blocked:** ${ctx.blockedTasks}  · **Overdue:** ${ctx.overdueTasks}\n\n## Risks\n${risks}\n\n## Next\n${next}${FOOTER}`,
  };
}
